"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

import os
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

MEDIA_URL = 'media/'
STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'test/']


# Django Constance module
CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r%x&ah7%7idgh)ml=z3n-rgkgs@b4)emge2*vy4#hw^_+o)r%!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['www.peresvet-safonovo.ru', '95.163.240.43', 'localhost']


# Application definition

INSTALLED_APPS = [
    'index.apps.IndexConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'constance',
]

CONSTANCE_IGNORE_ADMIN_VERSION_CHECK = True

CONSTANCE_CONFIG = {
    'TEXT_1': ('Идея тренировать подростков возникла в Сергеева Олега Владимировича еще 19 лет назад, позже она переросла в спортивной клуб Пересвет, который начал свою работу в п. Горный. Сейчас в клубе более 60 воспитанников, с которыми занимаются два тренера Сергеев Олег Владимирович и Сергеев Данила Олегович. Воспитанники участвуют в соревнованиях, в клуб часто приходят взрослые ребята боксеры и ветераны бокса, которые дают мастер-классы для воспитанников, помогают ребятам готовиться к соревнованиям. Сейчас клуб активно развивается, набирая разные возрастные группы от 7 до 59 лет. ', 'Текст по левой части наверху страницы'),
    # 'HEADER_1': (),
    'TEXT_2': ('Тренируем мужчин, девушек и детей. Прокачиваем силу, форму и уверенность в себе. Занимаемся персонально, в группах и мини-группах. Уровень подготовки не важен, важна ваша цель.', 'Текст по правой части наверху страницы'),
    # 'HEADER_2': (),
    'VK': ('https://vk.com/id112448563', 'Контактная страница для ВКонтакте'),
    'CONTACT_PHONE': ('79517135772', 'Телефон для связи'),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
