# Generated by Django 4.2.1 on 2023-05-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_trainer_delete_trainers_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name': 'Тренер', 'verbose_name_plural': 'Тренеры'},
        ),
    ]
